# Generated by Django 3.0.6 on 2020-05-14 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.BigIntegerField()),
                ('acct', models.CharField(max_length=1024)),
                ('display_name', models.CharField(max_length=1024)),
                ('url', models.URLField()),
                ('avatar', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.URLField()),
                ('client_key', models.CharField(help_text='public identifier from the mastodon development settings', max_length=64, verbose_name='App Client Key/ID')),
                ('client_secret', models.CharField(max_length=64, verbose_name='App Client Secret')),
                ('access_token', models.CharField(max_length=64, verbose_name='Account Access Token')),
            ],
        ),
        migrations.CreateModel(
            name='Toot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.BigIntegerField(unique=True)),
                ('api_notification_id', models.BigIntegerField(null=True)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField()),
                ('content', models.TextField()),
                ('visibility', models.CharField(choices=[('public', 'public'), ('unlisted', 'unlisted'), ('private', 'private'), ('direct', 'direct')], max_length=8)),
                ('socialhub_id', models.CharField(max_length=128, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toots', to='tmastodon.Account')),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toots', to='tmastodon.Credential')),
                ('in_reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmastodon.Toot')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='credentials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='tmastodon.Credential'),
        ),
    ]
