# Generated by Django 3.0.6 on 2020-05-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmastodon', '0002_auto_20200514_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='url_template',
            field=models.CharField(blank=True, help_text='use any {toot_dict_field}: https://mastodonpy.readthedocs.io/en/stable/#toot-dicts', max_length=64, null=True, verbose_name='Template to construct URLs to toots'),
        ),
    ]
