# Generated by Django 3.0.6 on 2020-05-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmastodon', '0005_auto_20200526_0753'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='toot',
            name='toot API id per server',
        ),
        migrations.AddConstraint(
            model_name='toot',
            constraint=models.UniqueConstraint(fields=('api_id', 'credentials'), name='unique-toot-api-id-per-server'),
        ),
    ]
