# Generated by Django 3.0.6 on 2020-05-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmastodon', '0006_auto_20200526_0800'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='account API id per server',
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('api_id', 'credentials'), name='unique-account-api-id-per-server'),
        ),
    ]
