# Generated by Django 3.0.6 on 2020-05-14 11:17

from django.db import migrations, models
import django.db.models.deletion
import tootsupport.tsocialhub.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tmastodon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesstoken', models.CharField(max_length=1024)),
                ('webhook_secret', models.CharField(default=tootsupport.tsocialhub.models.generate_webhook_secret, max_length=255)),
                ('mastodon_credentials', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tmastodon.Credential')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reply', 'Reply')], max_length=5)),
                ('action_id', models.CharField(max_length=255)),
                ('payload', models.TextField()),
                ('handled', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='tsocialhub.SyncTask')),
                ('toot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmastodon.Toot')),
            ],
        ),
    ]
